apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: requester
  name: requester
spec:
  ports:
  - port: 3333
    protocol: UDP
    targetPort: 3333
  selector:
    app: requester
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: receiver
  name: receiver
spec:
  ports:
  - port: 4444
    protocol: UDP
    targetPort: 4444
  selector:
    app: receiver
